kind = "web"
previewPath = "/"
title = "Elkanawy OS"
version = "1.0.0"
id = "artifacts/elkanawy-os"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24430

[services.development]
run = "pnpm --filter @workspace/elkanawy-os run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/elkanawy-os", "run", "build" ]
publicDir = "artifacts/elkanawy-os/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24430"
BASE_PATH = "/"
